version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ../scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: task-manager
    build:
      context: ../
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      SERVER_HOST: api
      SERVER_PORT: 3000
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    links:
      - db
volumes:
  db:
    driver: local
